version: '3'

services:
  flask_app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - flask_app
