version: '3'

services:

  flask_app: 
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - proxy

  nginx_flask:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    container_name: nginx_flask
    ports:
      - 80:80
    depends_on:
      - flask_app
    networks:
      - proxy


networks:
  proxy:
    driver: bridge
  