services:
  flask_app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - elojas_net

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - flask_app
    networks:
      - elojas_net

networks:
  elojas_net:
    name: elojas_net