events {
    worker_connections 1024;
}

http {
    include /etc/nginx/conf.d/*.conf;
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m inactive=60m;
    proxy_cache_key "$scheme$host$request_uri";

    upstream flask_app {
        server flask_app:8000;
    }

    server {
        listen 8080;

        proxy_cache my_cache;   

        proxy_cache_valid 200 30m;
        add_header X-Proxy-Cache $upstream_cache_status;
        # more_set_headers 'Strict-Transport-Security: max-age=10886400; includeSubDomains; preload';
        # more_set_headers 'X-Frame-Options: SAMEORIGIN';
        # more_set_headers 'X-XSS-Protection: 1; mode=block';
        # more_set_headers 'X-Content-Type-Options: nosniff';
        # more_set_headers 'Content-Security-Policy: upgrade-insecure-requests';

        location /nocache {
            proxy_pass http://flask_app/nocache;
        }

        location /cache {
            proxy_pass http://flask_app/cache;

        }

        location / {
            proxy_pass http://pudim.com.br/;
        }
    }
}